server:
  port: 8900
spring:
  application:
    name: api
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schemas/security.sql
        - classpath:schemas/common.sql
        - classpath:schemas/skills.sql
      data-locations:
        - classpath:data/security.sql
        - classpath:data/common.sql
        - classpath:data/skills.sql
  rabbitmq:
    host: capybara-01.lmq.cloudamqp.com
    username: xhuvvxgb
    password: 0qhot8tm9uAb1I1tmiw_cOX_VoB9fWCW
    virtual-host: xhuvvxgb
    ssl:
      enabled: true

rabbitmq:
  outbox:
    bindings:
      "[org.example.staffskillsauditor2.skills.domain.events.StaffMemberRegisteredEvent]":
        exchange: "staff-management"
        routing-key: "staffRegisteredKey"
firebase:
  web-api-key: "AIzaSyAv24cfVsap6Cfw7vBTp3Bn9TBEpIy1V2s"
