package org.example.staffskillsauditor2.common;

import org.example.staffskillsauditor2.common.domain.Identity;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("Identity value object unit tests")
public class IdentityTests {
    private static final class TestContext {}

    @Test
    @DisplayName("An identity cannot be created with a blank identifier")
    void identityCannotBeCreatedWithBlankIdentifier(){
        Throwable exception = assertThrows(IllegalArgumentException.class, () ->
                Identity.<TestContext>of("")
        );
        assertEquals(Identity.IDENTITY_NOT_EMPTY, exception.getMessage());
    }

    @Test
    @DisplayName("An identity cannot be created with a null identifier")
    void identityCannotBeCreatedWithNullIdentifier(){
        Throwable exception = assertThrows(IllegalArgumentException.class, () ->
                Identity.<TestContext>of(null)
        );
        assertEquals(Identity.IDENTITY_NOT_EMPTY, exception.getMessage());
    }

    @Test
    @DisplayName("An identity encapsulates its text value")
    void identityHasATextValue(){
        // 8-4-4-4-12 digits
        final String VALID_UUID_FORMAT = "00000000-0000-0000-0000-000000000001";
        Identity<TestContext> identity = Identity.of(VALID_UUID_FORMAT);

        assertDoesNotThrow(() -> UUID.fromString(identity.id()));
        assertEquals(VALID_UUID_FORMAT, identity.id());
    }

    @Test
    @DisplayName("New identities are generated by the system are UUID")
    void identitiesGeneratedByTheSystemAsUUID() {
        Identity<TestContext> generatedIdentity = Identity.generateId();

        assertDoesNotThrow(() -> UUID.fromString(generatedIdentity.id()));
    }
}