package org.example.staffskillsauditor2.portfolio.domain;

import org.example.staffskillsauditor2.common.domain.Identity;
import org.example.staffskillsauditor2.portfolio.domain.events.SkillAllocatedEvent;
import org.example.staffskillsauditor2.portfolio.domain.events.SkillRejectedEvent;
import org.example.staffskillsauditor2.portfolio.domain.events.SkillUnverifiedEvent;
import org.example.staffskillsauditor2.portfolio.domain.events.SkillVerifiedEvent;
import org.example.staffskillsauditor2.portfolio.domain.exceptions.SkillNotFoundException;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("SkillPortfolio Domain Unit Tests")
class SkillPortfolioUnitTests {

    private static final String STAFF_ID = "STAFF001";
    private static final String SKILL_ID = "SKILL001";

    private SkillPortfolio createEmptyPortfolio() {
        return SkillPortfolio.portfolioOf(
                Identity.generateId(),
                STAFF_ID,
                new ArrayList<>()
        );
    }

    private SkillPortfolio createPortfolioWithSkill() {
        SkillPortfolio portfolio = createEmptyPortfolio();

        portfolio.allocateSkill(
                SKILL_ID,
                3,
                "Java experience"
        );

        // Clear the event generated during setup so tests
        // can focus on the event generated by the action being tested.
        portfolio.clearDomainEvents();

        return portfolio;
    }

    @Nested
    @DisplayName("Portfolio creation")
    class CreationTests {

        @Test
        @DisplayName("Should create an empty portfolio")
        void shouldCreateEmptyPortfolio() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            assertNotNull(portfolio);
            assertEquals(STAFF_ID, portfolio.staffId());
            assertNotNull(portfolio.entries());
            assertTrue(portfolio.entries().isEmpty());
        }

        @Test
        @DisplayName("Should create portfolio with existing entries")
        void shouldCreatePortfolioWithExistingEntries() {
            PortfolioEntry entry =
                    new PortfolioEntry(SKILL_ID, 3, "Java experience");

            SkillPortfolio portfolio =
                    SkillPortfolio.portfolioOf(
                            Identity.generateId(),
                            STAFF_ID,
                            new ArrayList<>(List.of(entry))
                    );

            assertEquals(1, portfolio.entries().size());
            assertEquals(
                    SKILL_ID,
                    portfolio.entries().getFirst().skillId()
            );
        }

        @Test
        @DisplayName("Should create empty portfolio when entries are null")
        void nullEntriesShouldCreateEmptyList() {
            SkillPortfolio portfolio =
                    SkillPortfolio.portfolioOf(
                            Identity.generateId(),
                            STAFF_ID,
                            null
                    );

            assertNotNull(portfolio.entries());
            assertTrue(portfolio.entries().isEmpty());
        }
    }

    @Nested
    @DisplayName("Skill allocation")
    class AllocationTests {

        @Test
        @DisplayName("Should allocate a skill")
        void shouldAllocateSkill() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            portfolio.allocateSkill(
                    SKILL_ID,
                    3,
                    "Java experience"
            );

            assertEquals(1, portfolio.entries().size());

            PortfolioEntry entry = portfolio.entries().getFirst();

            assertEquals(SKILL_ID, entry.skillId());
            assertEquals(3, entry.skillLevel());
            assertEquals(
                    "Java experience",
                    entry.notes()
            );
            assertEquals(
                    VerificationStatus.PENDING,
                    entry.verificationStatus()
            );
        }

        @Test
        @DisplayName("Should accept minimum skill level")
        void shouldAcceptMinimumSkillLevel() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            assertDoesNotThrow(() ->
                    portfolio.allocateSkill(
                            SKILL_ID,
                            1,
                            "Beginner"
                    )
            );

            assertEquals(
                    1,
                    portfolio.entries().getFirst().skillLevel()
            );
        }

        @Test
        @DisplayName("Should accept maximum skill level")
        void shouldAcceptMaximumSkillLevel() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            assertDoesNotThrow(() ->
                    portfolio.allocateSkill(
                            SKILL_ID,
                            5,
                            "Expert"
                    )
            );

            assertEquals(
                    5,
                    portfolio.entries().getFirst().skillLevel()
            );
        }

        @Test
        @DisplayName("Should reject skill level below 1")
        void shouldRejectSkillLevelBelowMinimum() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            IllegalArgumentException exception =
                    assertThrows(
                            IllegalArgumentException.class,
                            () -> portfolio.allocateSkill(
                                    SKILL_ID,
                                    0,
                                    "Invalid level"
                            )
                    );

            assertEquals(
                    "Skill level must be between 1 and 5",
                    exception.getMessage()
            );

            assertTrue(portfolio.entries().isEmpty());
        }

        @Test
        @DisplayName("Should reject skill level above 5")
        void shouldRejectSkillLevelAboveMaximum() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            IllegalArgumentException exception =
                    assertThrows(
                            IllegalArgumentException.class,
                            () -> portfolio.allocateSkill(
                                    SKILL_ID,
                                    6,
                                    "Invalid level"
                            )
                    );

            assertEquals(
                    "Skill level must be between 1 and 5",
                    exception.getMessage()
            );

            assertTrue(portfolio.entries().isEmpty());
        }

        @Test
        @DisplayName("Should reject duplicate skill")
        void shouldRejectDuplicateSkill() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            IllegalArgumentException exception =
                    assertThrows(
                            IllegalArgumentException.class,
                            () -> portfolio.allocateSkill(
                                    SKILL_ID,
                                    4,
                                    "Duplicate"
                            )
                    );

            assertEquals(
                    "Skill already exists in this portfolio",
                    exception.getMessage()
            );

            assertEquals(1, portfolio.entries().size());
            assertEquals(
                    3,
                    portfolio.entries().getFirst().skillLevel()
            );
        }

        @Test
        @DisplayName("Should raise SkillAllocatedEvent when skill is allocated")
        void shouldRaiseSkillAllocatedEvent() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            portfolio.allocateSkill(
                    SKILL_ID,
                    4,
                    "Java experience"
            );

            assertEquals(1, portfolio.domainEvents.size());

            assertInstanceOf(
                    SkillAllocatedEvent.class,
                    portfolio.domainEvents.getFirst()
            );

            SkillAllocatedEvent event =
                    (SkillAllocatedEvent)
                            portfolio.domainEvents.getFirst();

            assertEquals(STAFF_ID, event.getStaffId());
            assertEquals(SKILL_ID, event.getSkillId());
            assertEquals(4, event.getSkillLevel());
            assertEquals(
                    "Java experience",
                    event.getNotes()
            );
        }
    }

    @Nested
    @DisplayName("Skill editing")
    class EditingTests {

        @Test
        @DisplayName("Should edit an existing skill")
        void shouldEditExistingSkill() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            portfolio.editSkill(
                    SKILL_ID,
                    5,
                    "Updated experience"
            );

            PortfolioEntry entry =
                    portfolio.entries().getFirst();

            assertEquals(5, entry.skillLevel());
            assertEquals(
                    "Updated experience",
                    entry.notes()
            );
            assertEquals(
                    VerificationStatus.PENDING,
                    entry.verificationStatus()
            );
        }

        @Test
        @DisplayName("Should reject editing a missing skill")
        void shouldRejectEditingMissingSkill() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            assertThrows(
                    SkillNotFoundException.class,
                    () -> portfolio.editSkill(
                            "UNKNOWN",
                            4,
                            "Updated"
                    )
            );

            assertTrue(portfolio.entries().isEmpty());
        }

        @Test
        @DisplayName("Should reject invalid level when editing")
        void shouldRejectInvalidEditLevel() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            IllegalArgumentException exception =
                    assertThrows(
                            IllegalArgumentException.class,
                            () -> portfolio.editSkill(
                                    SKILL_ID,
                                    6,
                                    "Invalid"
                            )
                    );

            assertEquals(
                    "Skill level must be between 1 and 5",
                    exception.getMessage()
            );

            assertEquals(
                    3,
                    portfolio.entries().getFirst().skillLevel()
            );
        }
    }

    @Nested
    @DisplayName("Skill verification")
    class VerificationTests {

        @Test
        @DisplayName("Should verify an existing skill")
        void shouldVerifySkill() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            portfolio.verifySkill(
                    SKILL_ID,
                    "manager1"
            );

            PortfolioEntry entry =
                    portfolio.entries().getFirst();

            assertEquals(
                    VerificationStatus.VERIFIED,
                    entry.verificationStatus()
            );
            assertEquals(
                    "manager1",
                    entry.verifiedBy()
            );
            assertNotNull(entry.verifiedOn());
        }

        @Test
        @DisplayName("Should reject verification of missing skill")
        void shouldRejectVerificationOfMissingSkill() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            assertThrows(
                    SkillNotFoundException.class,
                    () -> portfolio.verifySkill(
                            "UNKNOWN",
                            "manager1"
                    )
            );
        }

        @Test
        @DisplayName("Should reject blank verifier")
        void shouldRejectBlankVerifier() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            IllegalArgumentException exception =
                    assertThrows(
                            IllegalArgumentException.class,
                            () -> portfolio.verifySkill(
                                    SKILL_ID,
                                    "   "
                            )
                    );

            assertEquals(
                    "Verifier cannot be blank",
                    exception.getMessage()
            );

            assertEquals(
                    VerificationStatus.PENDING,
                    portfolio.entries()
                            .getFirst()
                            .verificationStatus()
            );
        }

        @Test
        @DisplayName("Should raise SkillVerifiedEvent")
        void shouldRaiseSkillVerifiedEvent() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            portfolio.verifySkill(
                    SKILL_ID,
                    "manager1"
            );

            assertEquals(1, portfolio.domainEvents.size());

            assertInstanceOf(
                    SkillVerifiedEvent.class,
                    portfolio.domainEvents.getFirst()
            );

            SkillVerifiedEvent event =
                    (SkillVerifiedEvent)
                            portfolio.domainEvents.getFirst();

            assertEquals(STAFF_ID, event.getStaffId());
            assertEquals(SKILL_ID, event.getSkillId());
            assertEquals(
                    "manager1",
                    event.getVerifiedBy()
            );
            assertNotNull(event.getVerifiedOn());
        }
    }

    @Nested
    @DisplayName("Skill unverification")
    class UnverificationTests {

        @Test
        @DisplayName("Should unverify a verified skill")
        void shouldUnverifySkill() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            portfolio.verifySkill(
                    SKILL_ID,
                    "manager1"
            );

            portfolio.clearDomainEvents();

            portfolio.unverifySkill(SKILL_ID);

            PortfolioEntry entry =
                    portfolio.entries().getFirst();

            assertEquals(
                    VerificationStatus.PENDING,
                    entry.verificationStatus()
            );
            assertNull(entry.verifiedBy());
            assertNull(entry.verifiedOn());
        }

        @Test
        @DisplayName("Should reject unverifying a missing skill")
        void shouldRejectUnverifyingMissingSkill() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            assertThrows(
                    SkillNotFoundException.class,
                    () -> portfolio.unverifySkill("UNKNOWN")
            );
        }

        @Test
        @DisplayName("Should raise SkillUnverifiedEvent")
        void shouldRaiseSkillUnverifiedEvent() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            portfolio.verifySkill(
                    SKILL_ID,
                    "manager1"
            );

            portfolio.clearDomainEvents();

            portfolio.unverifySkill(SKILL_ID);

            assertEquals(1, portfolio.domainEvents.size());

            assertInstanceOf(
                    SkillUnverifiedEvent.class,
                    portfolio.domainEvents.getFirst()
            );

            SkillUnverifiedEvent event =
                    (SkillUnverifiedEvent)
                            portfolio.domainEvents.getFirst();

            assertEquals(STAFF_ID, event.getStaffId());
            assertEquals(SKILL_ID, event.getSkillId());
        }
    }

    @Nested
    @DisplayName("Skill rejection")
    class RejectionTests {

        @Test
        @DisplayName("Should reject an existing skill")
        void shouldRejectSkill() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            portfolio.rejectSkill(
                    SKILL_ID,
                    "manager1"
            );

            PortfolioEntry entry =
                    portfolio.entries().getFirst();

            assertEquals(
                    VerificationStatus.REJECTED,
                    entry.verificationStatus()
            );
            assertEquals(
                    "manager1",
                    entry.verifiedBy()
            );
            assertNotNull(entry.verifiedOn());
        }

        @Test
        @DisplayName("Should reject rejection of missing skill")
        void shouldRejectMissingSkill() {
            SkillPortfolio portfolio = createEmptyPortfolio();

            assertThrows(
                    SkillNotFoundException.class,
                    () -> portfolio.rejectSkill(
                            "UNKNOWN",
                            "manager1"
                    )
            );
        }

        @Test
        @DisplayName("Should reject blank rejector")
        void shouldRejectBlankRejector() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            IllegalArgumentException exception =
                    assertThrows(
                            IllegalArgumentException.class,
                            () -> portfolio.rejectSkill(
                                    SKILL_ID,
                                    "   "
                            )
                    );

            assertEquals(
                    "Rejector cannot be blank",
                    exception.getMessage()
            );

            assertEquals(
                    VerificationStatus.PENDING,
                    portfolio.entries()
                            .getFirst()
                            .verificationStatus()
            );
        }

        @Test
        @DisplayName("Should raise SkillRejectedEvent")
        void shouldRaiseSkillRejectedEvent() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            portfolio.rejectSkill(
                    SKILL_ID,
                    "manager1"
            );

            assertEquals(1, portfolio.domainEvents.size());

            assertInstanceOf(
                    SkillRejectedEvent.class,
                    portfolio.domainEvents.getFirst()
            );

            SkillRejectedEvent event =
                    (SkillRejectedEvent)
                            portfolio.domainEvents.getFirst();

            assertEquals(STAFF_ID, event.getStaffId());
            assertEquals(SKILL_ID, event.getSkillId());
            assertEquals(
                    "manager1",
                    event.getRejectedBy()
            );
            assertNotNull(event.getRejectedOn());
        }
    }

    @Nested
    @DisplayName("Portfolio collection behaviour")
    class CollectionTests {

        @Test
        @DisplayName("Should expose entries as an unmodifiable list")
        void entriesShouldBeUnmodifiable() {
            SkillPortfolio portfolio =
                    createPortfolioWithSkill();

            assertThrows(
                    UnsupportedOperationException.class,
                    () -> portfolio.entries().clear()
            );

            assertEquals(1, portfolio.entries().size());
        }
    }

    @Test
    @DisplayName("Should not create event when editing missing skill fails")
    void failedEditShouldNotCreateEvent() {
        SkillPortfolio portfolio = createEmptyPortfolio();

        assertThrows(
                SkillNotFoundException.class,
                () -> portfolio.editSkill(
                        "UNKNOWN",
                        4,
                        "Updated"
                )
        );

        assertTrue(portfolio.domainEvents.isEmpty());
    }
}